### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Rishi556** [Someguy123/hivefeed-js#9]
Since this works with hive as well, the name is outdated. What about pricefeed-js?

**Comment by Rishi556** [comment]
<img width="845" alt="Screen Shot 2020-05-24 at 6 55 37 PM" src="https://user-images.githubusercontent.com/10539109/82767846-295e9e00-9df0-11ea-87f7-bfbf985a43ae.png">

**Comment by Someguy123** [comment]
`pricefeed-js` is too generic, would probably make it harder for users to find it when searching for `hive price feed` etc.

I've now renamed the repo to `hivefeed-js`
